DROP DATABASE IF EXISTS CHOZYS;

CREATE DATABASE CHOZYS
	DEFAULT CHARACTER SET utf8
	COLLATE utf8_spanish_ci;
	
USE CHOZYS;

CREATE TABLE MARCAS(
	IDMARCA			CHAR(10) NOT NULL,
	NOMBREMARCA		VARCHAR(50) NOT NULL,
	ESTADO			CHAR(1) NOT NULL,
	CONSTRAINT PK_IDMARCA_MAR PRIMARY KEY(IDMARCA),
	CONSTRAINT UK_NOMBREMARCA_MAR UNIQUE(NOMBREMARCA)
);

CREATE TABLE CATEGORIAS(
	IDCATEGORIA		CHAR(10) NOT NULL,
	NOMBRECATEGORIA		VARCHAR(50) NOT NULL,
	ESTADO			CHAR(1) NOT NULL,
	CONSTRAINT PK_IDCATEGORIA_CAT PRIMARY KEY(IDCATEGORIA),
	CONSTRAINT UK_NOMBRECATEGORIA_CAT UNIQUE(NOMBRECATEGORIA)
);

CREATE TABLE PRODUCTOS(
	IDPRODUCTO		CHAR(10) NOT NULL,
	IDCATEGORIA		CHAR(10) NOT NULL,
	IDMARCA			CHAR(10) NOT NULL,
	DESCRIPCION		VARCHAR(200) NOT NULL,
	PRECIO			DECIMAL(5,2) NOT NULL,
	IMAGEN			VARCHAR(100) NULL,
	ESTADO			CHAR(1) NOT NULL,
	CONSTRAINT PK_IDPRODUCTO_PRO PRIMARY KEY(IDPRODUCTO),
	CONSTRAINT FK_IDCATEGORIA_PRO FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
	CONSTRAINT FK_IDMARCA_PRO FOREIGN KEY(IDMARCA) REFERENCES MARCA(IDMARCA),
	CONSTRAINT UK_DESCRIPCION_PRO UNIQUE(DESCRIPCION)
);


/*****************************************************************************************************/
			/*P R O C E D I M I E N T O S   A L M A C E N A D O S*/
/*****************************************************************************************************/

/***********************************************************/
			/*M A R C A S*/
/***********************************************************/
DELIMITER $$
CREATE PROCEDURE SPU_INSERTAR_MARCAS(
	IN _NOMBREMARCA		VARCHAR(50)
)
BEGIN
	DECLARE _IDMARCA CHAR(10);
	SET _IDMARCA = (SELECT CONCAT('MAR',RIGHT(CONCAT('0000000',COUNT(*) + 1),7)) FROM MARCAS);
	INSERT INTO MARCAS (IDMARCA, NOMBREMARCA, ESTADO)
			VALUES (_IDMARCA, UPPER(_NOMBREMARCA), 1);
END $$

DELIMITER $$
CREATE PROCEDURE SPU_EDITAR_MARCAS(
	IN _NOMBREMARCA		VARCHAR(50),
	IN _IDMARCA		CHAR(10)
)
BEGIN
	UPDATE MARCAS SET
		NOMBREMARCA = UPPER(_NOMBREMARCA)
	WHERE IDMARCA = _IDMARCA;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_ESTADO_MARCAS(
	IN _IDMARCA		CHAR(10),
	IN _ESTADO		CHAR(1)
)
BEGIN
	UPDATE MARCAS SET
		ESTADO = _ESTADO
	WHERE IDMARCA = _IDMARCA;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_LISTAR_MARCAS(
	IN _ESTADO		CHAR(1)
)
BEGIN
	SELECT * FROM MARCAS
	WHERE ESTADO = _ESTADO;
END $$



/***********************************************************/
			/*C A T E G O R I A S*/
/***********************************************************/
DELIMITER $$
CREATE PROCEDURE SPU_INSERTAR_CATEGORIAS(
	IN _NOMBRECATEGORIA		VARCHAR(50)
)
BEGIN
	DECLARE _IDCATEGORIA CHAR(10);
	SET _IDCATEGORIA = (SELECT CONCAT('CAT',RIGHT(CONCAT('0000000',COUNT(*) + 1),7)) FROM CATEGORIAS);
	INSERT INTO CATEGORIAS(IDCATEGORIA, NOMBRECATEGORIA, ESTADO)
		VALUES(_IDCATEGORIA, UPPER(_NOMBRECATEGORIA), 1);
END $$

DELIMITER $$
CREATE PROCEDURE SPU_EDITAR_CATEGORIAS(
	IN _NOMBRECATEGORIA		VARCHAR(50),
	IN _IDCATEGORIA			CHAR(10)
)
BEGIN
	UPDATE CATEGORIAS SET
		NOMBRECATEGORIA = UPPER(_NOMBRECATEGORIA)
	WHERE IDCATEGORIA = _IDCATEGORIA;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_ESTADO_CATEGORIAS(
	IN _IDCATEGORIA		CHAR(10),
	IN _ESTADO		CHAR(1)
)
BEGIN
	UPDATE CATEGORIAS SET
		ESTADO = _ESTADO
	WHERE IDCATEGORIA = _IDCATEGORIA;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_LISTAR_CATEGORIAS(
	IN _ESTADO			CHAR(1)
)
BEGIN
	SELECT * FROM CATEGORIAS
	WHERE ESTADO = _ESTADO;
END $$



/***********************************************************/
			/*P R O D U C T O S*/
/***********************************************************/
DELIMITER $$
CREATE PROCEDURE SPU_INSERTAR_PRODUCTOS(
	IN _IDCATEGORIA			CHAR(10),
	IN _IDMARCA			CHAR(10),
	IN _DESCRIPCION			VARCHAR(200),
	IN _PRECIO			DECIMAL(5,2),
	IN _IMAGEN			VARCHAR(100)
)
BEGIN
	DECLARE _IDPRODUCTO CHAR(10);
	SET _IDPRODUCTO = (SELECT CONCAT('PRO',RIGHT(CONCAT('0000000',COUNT(*) + 1),7)) FROM PRODUCTOS);
	INSERT INTO PRODUCTOS(IDPRODUCTO, IDCATEGORIA, IDMARCA, DESCRIPCION, PRECIO, IMAGEN, ESTADO)
			VALUES(_IDPRODUCTO, _IDCATEGORIA, _IDMARCA, UPPER(_DESCRIPCION), _PRECIO, _IMAGEN, 1);
END $$

DELIMITER $$
CREATE PROCEDURE SPU_EDITAR_PRODUCTOS(
	IN _IDCATEGORIA			CHAR(10),
	IN _IDMARCA			CHAR(10),
	IN _DESCRIPCION			VARCHAR(200),
	IN _PRECIO			DECIMAL(5,2),
	IN _IMAGEN			VARCHAR(100),
	IN _IDPRODUCTO			CHAR(10)
)
BEGIN
	UPDATE PRODUCTOS SET
		IDCATEGORIA = _IDCATEGORIA,
		IDMARCA = _IDMARCA,
		DESCRIPCION = UPPER(_DESCRIPCION),
		PRECIO = _PRECIO,
		IMAGEN = _IMAGEN
	WHERE IDPRODUCTO = _IDPRODUCTO;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_ESTADO_PRODUCTOS(
	IN _IDPRODUCTO			CHAR(10),
	IN _ESTADO			CHAR(1)
)
BEGIN
	UPDATE PRODUCTOS SET
		ESTADO = _ESTADO
	WHERE IDPRODUCTO = _IDPRODUCTO;
END $$

DELIMITER $$
CREATE PROCEDURE SPU_LISTAR_PRODUCTOS(
	IN _ESTADO			CHAR(1)
)
BEGIN
	SELECT IDPRODUCTO, NOMBRECATEGORIA, NOMBREMARCA, DESCRIPCION, PRECIO, IMAGEN, PRODUCTOS.ESTADO FROM PRODUCTOS
	INNER JOIN MARCAS
	ON MARCAS.IDMARCA = PRODUCTOS.IDMARCA
	INNER JOIN CATEGORIAS
	ON CATEGORIAS.IDCATEGORIA = PRODUCTOS.IDCATEGORIA
	WHERE PRODUCTOS.ESTADO = _ESTADO;
END $$



/*P R O B A N D O   M A R C A S*/
/*
CALL SPU_INSERTAR_MARCAS ('ARTESCO');
CALL SPU_INSERTAR_MARCAS ('FABER-CASTELL');
CALL SPU_INSERTAR_MARCAS ('LAYCONSA');
CALL SPU_INSERTAR_MARCAS ('MONGOL');
CALL SPU_INSERTAR_MARCAS ('STABILO');

SELECT * FROM MARCAS;
*/


/*P R O B A N D O   C A T E G O R I A S*/
/*
CALL SPU_INSERTAR_CATEGORIAS ('CUADERNO');
CALL SPU_INSERTAR_CATEGORIAS ('LAPIZ');
CALL SPU_INSERTAR_CATEGORIAS ('LAPICERO');
CALL SPU_INSERTAR_CATEGORIAS ('HOJAS BOND');
CALL SPU_INSERTAR_CATEGORIAS ('LUSTRES');

SELECT * FROM CATEGORIAS;
*/



/*P R O B A N D O   P R O D U C T O S*/
/*
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000001', 'MAR0000001', 'CUADERNOS ARTESCO', 4.50, 'IMAGEN_1');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000002', 'MAR0000002', 'LAPIZ FABER-CASTELL', 1.50, 'IMAGEN_2');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000003', 'MAR0000003', 'LAPICERO LAYCONSA', 3.50, 'IMAGEN_3');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000004', 'MAR0000004', 'HOJAS BOND MONGOL', 11.50, 'IMAGEN_4');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000005', 'MAR0000005', 'PAPEL LUSTRE STABILO', 2.50, 'IMAGEN_5');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000001', 'MAR0000001', 'CUADERNOS ARTESCO 1', 4.50, 'IMAGEN_6');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000002', 'MAR0000002', 'LAPIZ FABER-CASTELL 1', 1.50, 'IMAGEN_7');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000003', 'MAR0000003', 'LAPICERO LAYCONSA 1', 3.50, 'IMAGEN_8');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000004', 'MAR0000004', 'HOJAS BOND MONGOL 1', 11.50, 'IMAGEN_9');
CALL SPU_INSERTAR_PRODUCTOS ('CAT0000005', 'MAR0000005', 'PAPEL LUSTRE STABILO 1', 2.50, 'IMAGEN_10');

SELECT * FROM PRODUCTOS;
*/



/*CALL SPU_LISTAR_PRODUCTOS(1);*/